import jsPDF from 'jspdf';
import 'jspdf-autotable';

const generateCustomPDF = (tickets, fromDate, toDate, locationFilter) => {
  const doc = new jsPDF();

  // Add the logo
  const logoPath = '/kumira-ghat.png';
  doc.addImage(logoPath, 'PNG', 30, 5, 25, 25);

  // Title and Date Range
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text("Kumira Guptachara Counter Report", 105, 15, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  doc.text(`Date Range: ${fromDate.toLocaleDateString()} - ${toDate.toLocaleDateString()}`, 105, 25, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  doc.text(`Station: ${locationFilter}`, 105, 30, { align: "center" });

  // Convert fromDate and toDate to Date objects at 00:00:00 for precise comparison
  const startDate = new Date(fromDate.setHours(0, 0, 0, 0));
  const endDate = new Date(toDate.setHours(23, 59, 59, 999));

  // Filter tickets for bookings and refunds
  const bookingTickets = tickets.filter(ticket => {
    const bookingDate = new Date(ticket.bookingDate);
    return bookingDate >= startDate && bookingDate <= endDate;
  });

  const refundTickets = tickets.filter(ticket => {
    const editedDate = new Date(ticket.editedDate);
    return editedDate >= startDate && editedDate <= endDate;
  });

  // Bookings Table
  const bookingTableColumns = ["No", "Payment ID", "Booking Date", "Boat Type", "Pass", "Half", "Weight", "Cost"];
  const bookingTableRows = [];
  let totalAdultPassengers = 0;
  let totalHalfTicketPassengers = 0;

  bookingTickets.forEach((ticket, index) => {
    bookingTableRows.push([
      index + 1,
      ticket.paymentId,
      new Date(ticket.bookingDate).toLocaleDateString(),
      ticket.boatType,
      ticket.totalAdultPassengers || 0,
      ticket.totalHalfTicketPassengers || 0,
      ticket.baggageCount || 0,
      `${ticket.totalCost}`,
    ]);
    totalAdultPassengers += ticket.totalAdultPassengers || 0;
    totalHalfTicketPassengers += ticket.totalHalfTicketPassengers || 0;
  });

  const totalBookingCost = bookingTickets.reduce((acc, ticket) => acc + ticket.totalCost, 0);

  doc.autoTable({
    startY: 35,
    head: [bookingTableColumns],
    body: bookingTableRows,
    styles: {
      fontSize: 10,
      cellPadding: 1,
      valign: 'middle',
      halign: 'center',
      lineWidth: 0.1,
    },
    theme: 'grid',
    headStyles: {
      fillColor: '#47abbd',
      textColor: [255, 255, 255],
    },
  });

  // Add Total Cost for Bookings
  let currentY = doc.lastAutoTable.finalY + 5;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Total Cost (Bookings): ${totalBookingCost.toFixed(2)}`, 14, currentY);

  // Add Total Adult and Half-Ticket Passengers
  currentY += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Total Adult Passengers: ${totalAdultPassengers}`, 14, currentY);
  currentY += 5;
  doc.text(`Total Half-Ticket Passengers: ${totalHalfTicketPassengers}`, 14, currentY);

  // Refunds Table
  const refundTableColumns = ["No", "Payment ID", "Edited Date", "Boat Type", "Refund"];
  const refundTableRows = refundTickets.map((ticket, index) => [
    index + 1,
    ticket.paymentId,
    new Date(ticket.editedDate).toLocaleDateString(),
    ticket.boatType,
    ticket.afterRefund !== undefined ? ticket.afterRefund : "N/A",
  ]);

  const totalRefund = refundTickets.reduce((acc, ticket) => acc + (ticket.afterRefund || 0), 0);

  doc.autoTable({
    startY: currentY + 10,
    head: [refundTableColumns],
    body: refundTableRows,
    styles: {
      fontSize: 10,
      cellPadding: 1,
      valign: 'middle',
      halign: 'center',
      lineWidth: 0.1,
    },
    theme: 'grid',
    headStyles: {
      fillColor: '#47abbd',
      textColor: [255, 255, 255],
    },
  });

  // Add Total Refunds
  currentY = doc.lastAutoTable.finalY + 5;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Total Refund: ${totalRefund.toFixed(2)}`, 14, currentY);

  // Net Total
  const netTotal = totalBookingCost - totalRefund;
  currentY += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Net Total: ${netTotal.toFixed(2)}`, 14, currentY);

  // Signature
  const signatureLineY = currentY + 15;
  doc.setDrawColor(0, 0, 0);
  doc.line(105, signatureLineY, 165, signatureLineY);

  doc.setFontSize(10);
  doc.setFont("helvetica", "italic");
  doc.text("Approved by Azmaine Adil Chowdhury", 135, signatureLineY + 5, { align: "center" });

  // Footer
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by Kumira Guptachara Ferry System", 105, signatureLineY + 20, { align: "center" });

  // Save the PDF
  doc.save(`Counter_Tickets_Report_${fromDate.toLocaleDateString()}-${toDate.toLocaleDateString()}.pdf`);
};

export default generateCustomPDF;
